version: '3'
services:
    server:
      build: .
      command:
         python3 manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
      #useful in development to track the changes
      volumes:
        - ./backend:/code
      ports:
        - "8881:8000"
      env_file:
        - .env
      networks:
        - server_network
    db:
      image: postgis/postgis
      container_name: db
      ports:
        - "5438:5432"
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - ALLOW_IP_RANGE=0.0.0.0
      volumes:
        - postgres_data:/var/lib/postgresql
      networks:
        - server_network
    #
    front:
      build: ./frontend
      depends_on:
         - server
      # Mount the container `/drf` folder to the a `src` folder in the location
      # of the Dockerfile on the host machine.
      volumes:
         - ./frontend:/usr/src/app/
      restart: always
      stdin_open: true
      # Map port 3000 to port 8081 so that we can access the application on
      # our host machine by visiting 127.0.0.1:8081
      ports:
         - "8081:3000"
      networks:
        - server_network         
networks:
  server_network:
    driver: bridge

volumes:
  postgres_data:
